Vagrant.configure("2") do |config|
        config.vm.define "netbox" do |client|
            client.vm.box = "bento/centos-7.4"
            client.vm.provision "shell", inline: "sudo service network restart"
            client.vm.network "private_network", ip: "192.168.50.2"
        end
        config.vm.provision "ansible" do |ansible|
            ansible.playbook = "netbox.yml"
        end
        config.vm.synced_folder "/home/phil/git", "/git"
end
